export const STYLESHEET_KEY = 'FIBRE_PLANNER_STYLESHEET_V3';
export const GEOJSON_ZOOM_THRESHOLD = 15;

export const LAST_POSITION = 'FIBRE_PLANNER_LAST_MAP_POSITION';

export const TOGGLE_LAYER_EVENT = 'TOGGLE_LAYER_EVENT';